### ISSUE TITLE
is there a #define to know the board?

### ISSUE THREAD

**Issue by dmsherazi** [wasdpkj/Microduino-IDE-Support#1]
SANGUINO and MICRODUINO both use Atmega_644PA although they have completely different pin mappings.

PD6 is PIN 14 on sanguino, while on Microduino it is PIN 8

**Comment by wasdpkj** [comment]
pin Map：
http://wiki.microduino.cn/index.php/Microduino-Core%2B/zh

**Comment by dmsherazi** [comment]
what I mean is that If I write a library that can work with multiple arduino variants I can know if it by using #if defined as in this anwser http://electronics.stackexchange.com/a/58388/30657.

If I follow this  #if defined(**AVR_ATmega644PA**) will be true for both Sanguino as well as Microduino  core+.

**Comment by jflyper** [comment]
@dmsherazi 
I really believe that arduino{cc,org} provide a standardized way of distinguishing different implementations of the same processor, and board manufacturers follow the standards.

The world is not that simple, I guess.

Asymptotically speaking, by looking at two pins_arduino.h files, I can say the followings.
1. Core+ has CALUNIUM and CALUNIUM_VARIANT defined.
       CALUNIUM was never mass produced?
2. Core+ defines NUM_DIGITAL_PINS as 32, whereas Sanguino defines it as 24.
      #if defined(AVR_ATmega644PA) && (NUM_DIGITAL_PINS == 32)
