### ISSUE TITLE
platform.txt recipe.ar.pattern does not work on Linux

### ISSUE THREAD

**Issue by mattdm** [wasdpkj/Microduino-IDE-Support#4]
The file as shipped results in `{archive_file_path}: Permission denied` on Fedora. I found a solution at https://github.com/Robot-Will/Stino/issues/315, and this works; change `recipe.ar.pattern` to

```
recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}"
```

(Replacing `{archive_file_path}` with `{build.path}/{archive_file}`.)

**Comment by wasdpkj** [comment]
updata to 1.6.9
